import { Candidate } from "../service/page";

export const testcandidates: Candidate[] = [
  {
    id: "c1",
    initials: "AL",
    name: "Alice Lee",
    verified: true,
    policeCheck: true,
    agedCareTraining: true,
    languages: ["en", "zh"],
    gender: "female",
    skills: ["chat", "cooking", "gardening"],
    wardAccess: ["A1", "B2"],
    rating: 4.8,
  },
  {
    id: "c2",
    initials: "BM",
    name: "Ben Miller",
    verified: true,
    policeCheck: true,
    agedCareTraining: false,
    languages: ["en"],
    gender: "male",
    skills: ["gardening", "transport"],
    wardAccess: ["C3"],
    rating: 4.2,
  },
  {
    id: "c3",
    initials: "CS",
    name: "Cathy Sun",
    verified: false,
    policeCheck: false,
    agedCareTraining: true,
    languages: ["zh"],
    gender: "female",
    skills: ["chat", "cooking"],
    wardAccess: ["A2"],
    rating: 3.9,
  },
  {
    id: "c4",
    initials: "DJ",
    name: "David Johnson",
    verified: true,
    policeCheck: true,
    agedCareTraining: true,
    languages: ["en"],
    gender: "male",
    skills: ["gardening", "music"],
    wardAccess: ["B1", "C1"],
    rating: 4.5,
  },
  {
    id: "c5",
    initials: "ER",
    name: "Ella Rodriguez",
    verified: true,
    policeCheck: false,
    agedCareTraining: false,
    languages: ["es", "en"],
    gender: "female",
    skills: ["chat", "cooking", "teaching"],
    wardAccess: ["D1"],
    rating: 4.0,
  },
];
